### ISSUE TITLE
Needed dependencies

### ISSUE THREAD

**Issue by parkerlreed** [Iscle/SpaceCadetPinball#1]
app/src/main/cpp/SDL and SDL_Mixer don't seem to be included as sub-modules.

Is there a particular source tree I need to pull these from?

**Comment by iscle** [comment]
I've just pushed some changes. The commit history is a bit messy, I'd like to clean it up, but it builds and works! I've tested it on arm64 only.

**Comment by parkerlreed** [comment]
Success!

https://user-images.githubusercontent.com/841440/138027267-3339b124-48f6-475a-9830-c0a72791db23.mp4

**Comment by iscle** [comment]
I'll add settings to hide UI controls in case you're using an external keyboard
